spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_center?characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  profiles:
    active: dev
  application:
    name: user-center
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        cluster-name: beijing
server:
  port: 8081

# 配置rocketmq
rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    # 必须指定group
    group: test-grop
---

---